export const enum ResourceTypes {
	MENU_USERS = 'MENU_USERS',
	MENU_MEETS = 'MENU_MEETS',
	EVENTS = 'EVENTS',
	MENU_DOCS = 'MENU_DOCS',
	MENU_PROCEEDINGS = 'MENU_PROCEEDINGS',
	MENU_GROUP = 'MENU_GROUP',
	USERS = 'USERS',
	ROLES = 'ROLES',
	OFFICIAL = 'OFFICIAL',
	GROUP = 'GROUP',
	WORKING = 'WORKING',
	SYSTEM_PERMISSIONS = 'SYSTEM_PERMISSIONS',
	LOG_ACTIVITIES = 'LOG_ACTIVITIES',

	FIRE_MONITORING = 'FIRE_MONITORING',

	MENU_CARTOGRAPHIC = 'MENU_CARTOGRAPHIC',
	CARTOGRAPHIC_RESOURCES = 'CARTOGRAPHIC_RESOURCES',
	CARTOGRAPHIC_STYLES = 'CARTOGRAPHIC_STYLES',

	MENU_GEOVISOR = 'MENU_GEOVISOR',
	GEOVISOR = 'GEOVISOR',

	ATTACHMENTS = 'ATTACHMENTS',

	SESSIONS = 'SESSIONS',
	AGENDA = 'AGENDA',
}
