export const enum ResourceTypes {
	MENU_USERS = 'MENU_USERS',
	MENU_MEETS = 'MENU_MEETS',
	MENU_EVENTS = 'MENU_EVENTS',
	USERS = 'USERS',
	ROLES = 'ROLES',
	SYSTEM_PERMISSIONS = 'SYSTEM_PERMISSIONS',
	LOG_ACTIVITIES = 'LOG_ACTIVITIES',

	MENU_MONITORING = 'MENU_MONITORING',
	FIRE_MONITORING = 'FIRE_MONITORING',

	MENU_CARTOGRAPHIC = 'MENU_CARTOGRAPHIC',
	CARTOGRAPHIC_RESOURCES = 'CARTOGRAPHIC_RESOURCES',
	CARTOGRAPHIC_STYLES = 'CARTOGRAPHIC_STYLES',

	MENU_GEOVISOR = 'MENU_GEOVISOR',
	GEOVISOR = 'GEOVISOR',

	ATTACHMENTS = 'ATTACHMENTS',

	SESSIONS = 'SESSIONS',
	AGENDA = 'AGENDA',
}
